import { ArrowLeft, ArrowRight, BookOpen, Camera, ChevronDown, Copy, FileUp, Folder, LockKeyhole, ScanLine, Search, ShieldCheck } from 'lucide-react'
import { useEffect } from 'react'

type Destination = 'capture' | 'home' | 'actions' | 'folders' | 'settings' | 'trash'
const chapters = [
  { id: 'capture', icon: ScanLine, tone: 'green', title: 'Turn paper into searchable documents', summary: 'Scan, crop and recognise text on your device.', steps: ['Choose Scan on Home. Keep the page well lit and inside the frame.', 'Review the edges, crop or improve readability, then save your pages.', 'Your document is saved first. Text recognition continues on your device; wait for Searchable before searching its contents.'], note: 'Already have a PDF? Choose Import PDF on Home. Password-protected files ask for a password; you can choose to save an unlocked copy.', action: 'Scan a document', destination: 'capture' },
  { id: 'find', icon: Search, tone: 'blue', title: 'Find something you remember', summary: 'Search words inside documents, then jump to the page.', steps: ['Search a filename or a word from a document on Home.', 'Tap a result to open the matching page. Use search inside the viewer to find more matches.', 'Add folders and tags to organise related documents. Home starts with the last three weeks; choose All time in the date filter to see older files.'], note: 'Private documents stay out of global search. Authenticate to open one, then search within it.', action: 'Go to Home', destination: 'home' },
  { id: 'read', icon: BookOpen, tone: 'blue', title: 'Read comfortably', summary: 'Continuous pages, bookmarks and a simpler text view.', steps: ['Open a document and scroll continuously through its pages. Pinch to zoom.', 'Use reading options for text view and your preferred viewing mode.', 'Bookmark a useful page to return to it later without searching again.'], note: 'Text view uses recognised text. Scans with handwriting, faint print or complex layouts may need checking against the original.', action: 'Choose a document', destination: 'home' },
  { id: 'reuse', icon: Copy, tone: 'violet', title: 'Reuse just what you need', summary: 'Copy selected text or create a PDF from chosen pages.', steps: ['Open Tools → Extract text. Choose a document and select the pages you need.', 'Copy their text together, or export it as a text file.', 'Use Split or extract for selected PDF pages, or Combine PDFs to join documents in your chosen order.'], note: 'Your originals remain available when you create a copy.', action: 'Open document tools', destination: 'actions' },
  { id: 'share', icon: FileUp, tone: 'violet', title: 'Prepare a document to share', summary: 'Arrange pages, annotate and make smaller copies.', steps: ['Use Tools to reorder or insert pages, or review suggested blank and duplicate pages.', 'Open a document to annotate it. Choose whether to save a copy or update the original.', 'Compress a PDF when file size matters, then export or share the result. Review the filename and destination.'], note: 'Page tools and annotations do not edit existing PDF text. Newly generated PDFs may need their password protection reapplied before sharing.', action: 'Open document tools', destination: 'actions' },
  { id: 'protect', icon: LockKeyhole, tone: 'green', title: 'Protect and recover your documents', summary: 'Choose the protection that fits what you are doing.', steps: ['Mark a document private to require authentication inside LOCAL. App lock protects access to the whole app.', 'Use a PDF password to protect a PDF you export. This is separate from making a document private.', 'Create an encrypted backup in Settings and keep it somewhere safe. Store its passphrase separately; you will need it to restore.', 'Deleted documents remain in Recently Deleted for 30 days unless you delete them permanently.'], note: 'LOCAL does not automatically sync your library. A backup on the same phone will not protect you if that phone is lost.', action: 'Open Settings', destination: 'settings' },
] as const

export function DiscoverScreen({ onBack, onNavigate }: { onBack: () => void; onNavigate: (destination: Destination) => void }) {
  useEffect(() => {
    const back = (event: Event) => { event.preventDefault(); onBack() }
    window.addEventListener('local:back', back)
    return () => window.removeEventListener('local:back', back)
  }, [onBack])
  return <div className="discover-screen">
    <button className="discover-back" onClick={onBack}><ArrowLeft size={18} /> Back</button>
    <header className="discover-intro"><span className="discover-eyebrow">A LITTLE GUIDANCE. A LOT YOU CAN DO.</span><h1>Discover LOCAL</h1><p>From a pile of paper to the page you need. Start with one document and explore at your own pace.</p></header>
    <section className="discover-start" aria-labelledby="discover-start-title"><span className="discover-icon tone-green"><Camera /></span><div><h2 id="discover-start-title">Your first document</h2><p>Scan a page, save it, then find a word inside it once text recognition finishes.</p><button onClick={() => onNavigate('capture')}>Try a scan <ArrowRight size={17} /></button></div></section>
    <div className="discover-chapters">{chapters.map(chapter => <details key={chapter.id} className="discover-chapter"><summary><span className={`discover-icon tone-${chapter.tone}`}><chapter.icon /></span><span><strong>{chapter.title}</strong><small>{chapter.summary}</small></span><ChevronDown className="discover-chevron" size={19} /></summary><div className="discover-chapter-body"><ol>{chapter.steps.map(step => <li key={step}>{step}</li>)}</ol><p className="discover-note">{chapter.note}</p><button className="discover-action" onClick={() => onNavigate(chapter.destination)}>{chapter.action}<ArrowRight size={17} /></button></div></details>)}</div>
    <footer className="discover-trust"><ShieldCheck /><div><strong>On your device. In your control.</strong><p>Processing happens on your device. You choose what to export or share.</p></div></footer>
    <button className="discover-back" onClick={() => onNavigate('folders')}><Folder size={18} /> Organise your folders <ArrowRight size={17} /></button>
  </div>
}
